### ISSUE TITLE
demo with a bit more details?

### ISSUE THREAD

**Issue by justinyhuang** [alexcrichton/coz-rs#1]
i hope i am not asking for too much: would you mind showing some examples/demo on how to use the coz profiler, after the application is built with the coz crate?

Great work btw!

**Comment by alexcrichton** [comment]
A good question! Unfortunately this is still in the early stages and I haven't actually gotten any good graphs out of coz yet. I wanted to get the work up since I'm relatively certain this is a faithful translation of `coz.h`, but I honestly don't have any good demos nor do I know how best to integrate it into a program!

So in that sense I'd love to help here, but I'm not sure I can :(

**Comment by justinyhuang** [comment]
Thank you for the prompt response!
i cannot get any helpful output form coz either, so at least i know i am not alone ;)
please please keep us updated with future progress!

**Comment by philipc** [comment]
See https://github.com/plasma-umass/coz/issues/109#issuecomment-533853075 for a possible reason why it doesn't work.

**Comment by alexcrichton** [comment]
Ok I've gotten bits and pieces working better and I've got programs running through `coz` which are indeed generating graphs. I've attempted to add an `examples/toy.rs` to this repository as well to show off an example of using `coz`. If others have suggestions of example programs to add I'm all ears! Hopefully there's enough bare-bones to get started though.

@philipc good point! I don't think though that's preventing data from being captured, but it may mean that data captures are incorrect? (I'm not entirely sure)
