### ISSUE TITLE
when you get this working...

### ISSUE THREAD

**Issue by emeryberger** [alexcrichton/coz-rs#2]
...we'd be delighted to merge this into the main Coz repo!

**Comment by sanbox-irl** [comment]
Based on my own googling, the talk went up about 2 days ago on Youtube and then I immediately searched if a Rust version was available :D ! Either Alex was in the Room, or saw it the day it went up based on the commit stamps

**Comment by alexcrichton** [comment]
Thanks for the offer @emeryberger! I think I've got enough working now and while I'm still wrangling `coz` to get the most useful information, I believe the problem fully lies with me and my programs rather than this crate, so I've sent https://github.com/plasma-umass/coz/pull/112 to see what others think as well.
