### ISSUE TITLE
Why SeqCst instead of Rlx (or RelAcq)?

### ISSUE THREAD

**Issue by Janno** [alexcrichton/coz-rs#5]
https://github.com/alexcrichton/coz-rs/blob/2e781893d1e9206c6f5d39a442679013d17bfa4d/src/lib.rs#L208

The increment method uses Rlx in the orignal C header. Are you being conservative or is there a reason to assume that Rlx is too weak?

I only work(ed) on the theoretical side of weak memory models so I can't speak to the performance impact. However, I would be careful to avoid any unnecessary synchronization in a profiler meant to be used in a multithreaded setting.

P.S.: Thanks so much for writing these rust bindings. I look fordward to using them!

**Comment by alexcrichton** [comment]
Thanks for the question! My personal default for all atomics is `SeqCst` since I at least consider it the safest to use when you otherwise just want to not think about orderings at all. I suspect this can be relaxed much more, just didn't do it myself! 

FWIW the code for all this [now lives upstream](https://github.com/plasma-umass/coz/tree/master/rust) so I'm going to close this, but PRs there are more than welcome to change this!
